platform :ios, '11.0'

source 'https://github.com/dpostigo/pods'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'Andea_Example' do
  pod 'Andea', :path => '../'

  target 'Andea_Tests' do
    inherit! :search_paths
  end
end

